import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbarr from "./navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yohannes",
  description: "Generated by Yohannes Niguse",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-50 via-white to-gray-200 min-h-screen flex flex-col`}
      >
        <Navbarr />
        <main className="flex-1 container mx-auto px-4 py-8">{children}</main>
        <footer className="w-full text-center py-6 bg-white/80 backdrop-blur border-t border-gray-200 text-gray-600 text-sm font-mono">
          © {new Date().getFullYear()}{" "}
          <span className="font-semibold">Yohannes Niguse</span>. All rights
          reserved.
        </footer>
      </body>
    </html>
  );
}
